version: "3.9"
services:
  web:
    build: .
    command: bash -c "alembic upgrade head && cd ./services/crypto_tracker && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8008:8000"
    volumes:
      - .:/services/crypto_tracker
      - .:/services/coins_fetchers
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
        - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cryptodb

volumes:
  postgres_data:
